#!/bin/bash

set -e

# This shell script runs all of the WORKING tests that PASS.
# It will also remove all of the temporary files that are generated by the test
# cases.
# If any of the tests in this script FAIL, DO NOT PUSH YOUR CHANGES TO THE
# GITHUB REPOSITORY!

echo "./build/test/unittests/unittest-noseHoover"
./build/test/unittests/unittest-noseHoover

echo "./build/test/unittests/unittest-langevinPiston"
./build/test/unittests/unittest-langevinPiston

echo "./build/test/unittests/unittest-langevinThermostat"
./build/test/unittests/unittest-langevinThermostat

echo "./build/test/unittests/unittest-restart"
./build/test/unittests/unittest-restart

# unittest-noseHoover
rm -rf waterbox_1_s_new.dcd waterbox_1_s_old.dcd

# unittest-restart
rm -rf tmpNoseHoover.rst tmpLangevinPiston.rst tmpLangevinThermostat.rst
