list(APPEND src_files
  src/BEDSSubscriber.cu
  src/CharmmContext.cu
  src/Checkpoint.cu
  src/CheckpointSubscriber.cu
  src/Coordinates.cu
  src/CudaContainer.cu

  # src/Constraints.cu
  src/CudaBAOABIntegrator.cu
  src/CudaBondedForce.cu
  src/DynaSubscriber.cu
  src/EnergyVirial.cpp
  src/CudaEnergyVirial.cu
  src/cpp_utils.cu
  src/cpp_utils.cpp
  src/cuda_utils.cu
  src/CudaEMap.cu
  src/CudaPMEDirectForce.cu
  src/CudaDirectForceKernels.cu
  src/CudaPMEReciprocalForce.cu
  src/CudaPMEReciprocalGeneralForce.cu
  src/CudaHolonomicConstraint.cu
  src/CudaNeighborListBuild.cu
  src/CudaNeighborListSort.cu
  src/CudaNeighborList.cu
  src/CudaTopExcl.cu
  src/XYZQ.cu
  src/CudaPMERecip.cu
  src/DcdSubscriber.cu
  src/EDSForceManager.cu
  src/EDSSubscriber.cu
  src/Matrix3d.cu
  src/reduce.cu
  src/FEPSubscriber.cu
  src/Force.cu
  src/ForceManager.cu
  src/ForceManagerGenerator.cu

  # src/ForceType.cu
  src/CharmmCrd.cu
  src/CharmmParameters.cu
  src/CharmmPSF.cu
  src/CharmmResidueTopology.cu
  src/CudaIntegrator.cu
  src/CudaLangevinThermostatIntegrator.cu
  src/CudaLeapFrogIntegrator.cu
  src/CudaVerletIntegrator.cu
  src/CudaVMMSVelocityVerletIntegrator.cu
  src/CudaVelocityVerletIntegrator.cu
  src/CudaNoseHooverThermostatIntegrator.cu
  src/CudaLangevinPistonIntegrator.cu
  src/CudaP21NeighborListBuild.cu
  src/CudaExternalForce.cu
  src/CudaRestraintForce.cu
  src/CompositeSubscriber.cu
  src/DualTopologySubscriber.cu
  src/BEDSForceManager.cu
  src/GeometricRestraintForce.cu
  src/MBARSubscriber.cu
  src/FEPEIForceManager.cu
  src/MBARForceManager.cu
  src/CudaMinimizer.cu

  # src/MPIDForce.cu
  src/NetCDFSubscriber.cu
  src/PDB.cu
  src/PertForceManager.cu
  src/PrintEnergiesGraph.cu
  src/RestartSubscriber.cu
  src/ReplicaExchange.cu
  src/CudaIntegratorGraph.cu
  src/NeighborListSort.cu
  src/NonEquilibriumForceManager.cu
  src/SimpleLeapfrogGraph.cu
  src/StateSubscriber.cu
  src/Subscriber.cu
  src/DeviceVector.cu
  src/TestForce.cu
  src/TestSystem.cu
  src/XYZSubscriber.cu
  src/Utilities.cu
  src/Logger.cu
  src/tinyxml2.cpp
)
