# CMake generated Testfile for 
# Source directory: /u/samar/Documents/git/apocharmm/test/unittests
# Build directory: /u/samar/Documents/git/apocharmm/new_build/test/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unittest-charmmContext "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-charmmContext")
set_tests_properties(unittest-charmmContext PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-forceManager "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-forceManager")
set_tests_properties(unittest-forceManager PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-subscribers "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-subscribers")
set_tests_properties(unittest-subscribers PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-readCoordinates "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-readCoordinates")
set_tests_properties(unittest-readCoordinates PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-integrators "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-integrators")
set_tests_properties(unittest-integrators PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-readPRM "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-readPRM")
set_tests_properties(unittest-readPRM PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-restraintForce "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-restraintForce")
set_tests_properties(unittest-restraintForce PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-logger "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-logger")
set_tests_properties(unittest-logger PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-utils "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-utils")
set_tests_properties(unittest-utils PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-cudaContainers "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-cudaContainers")
set_tests_properties(unittest-cudaContainers PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-restart "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-restart")
set_tests_properties(unittest-restart PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-checkpoint "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-checkpoint")
set_tests_properties(unittest-checkpoint PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-eneForces "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-eneForces")
set_tests_properties(unittest-eneForces PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-holonomic "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-holonomic")
set_tests_properties(unittest-holonomic PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-p21 "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-p21")
set_tests_properties(unittest-p21 PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-langevinThermostat "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-langevinThermostat")
set_tests_properties(unittest-langevinThermostat PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-langevinPiston "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-langevinPiston")
set_tests_properties(unittest-langevinPiston PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-argon1000 "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-argon1000")
set_tests_properties(unittest-argon1000 PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-waterbox "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-waterbox")
set_tests_properties(unittest-waterbox PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-benchmarks "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-benchmarks")
set_tests_properties(unittest-benchmarks PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-insulin1 "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-insulin1")
set_tests_properties(unittest-insulin1 PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-alchemical "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-alchemical")
set_tests_properties(unittest-alchemical PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-fep "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-fep")
set_tests_properties(unittest-fep PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-eds "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-eds")
set_tests_properties(unittest-eds PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-bridgeEDS "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-bridgeEDS")
set_tests_properties(unittest-bridgeEDS PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-benzenePyrrole "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-benzenePyrrole")
set_tests_properties(unittest-benzenePyrrole PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-minimize "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-minimize")
set_tests_properties(unittest-minimize PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-pme "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-pme")
set_tests_properties(unittest-pme PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
add_test(unittest-replicaExchange "/u/samar/Documents/git/apocharmm/new_build/test/unittests/unittest-replicaExchange")
set_tests_properties(unittest-replicaExchange PROPERTIES  WORKING_DIRECTORY "/u/samar/Documents/git/apocharmm/new_build/test/unittests" _BACKTRACE_TRIPLES "/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;117;add_test;/u/samar/Documents/git/apocharmm/test/unittests/CMakeLists.txt;0;")
