// BEGINLICENSE
//
// This file is part of chcuda, which is distributed under the BSD 3-clause
// license, as described in the LICENSE file in the top level directory of this
// project.
//
// Author:  Samarjeet Prasad, James E. Gonzales II
//
// ENDLICENSE

#include "CharmmContext.h"
#include "DcdSubscriber.h"
#include <array>
#include <cstdio>
#include <iostream>

DcdSubscriber::DcdSubscriber(const std::string &fileName)
    : Subscriber(fileName) {
  m_NumFramesWritten = 0;
  m_IsHeaderWritten = false;
}

DcdSubscriber::DcdSubscriber(const std::string &fileName, int reportFrequency)
    : Subscriber(fileName, reportFrequency) {
  m_NumFramesWritten = 0;
  m_IsHeaderWritten = false;
}

DcdSubscriber::DcdSubscriber(const std::string &fileName, int reportFrequency,
                             std::shared_ptr<CharmmContext> ctx)
    : Subscriber(fileName, reportFrequency) {
  m_NumFramesWritten = 0;
  m_IsHeaderWritten = false;
  this->writeHeader();
}

DcdSubscriber::~DcdSubscriber(void) {
  if (m_FileStream.is_open())
    m_FileStream.close();
}

void DcdSubscriber::update(void) {
  // Write header if needed
  if (!m_IsHeaderWritten)
    this->writeHeader();

  // JEG250610: Add conditional statement for this
  this->writeXtalData();

  // Write coordinate data
  this->writeCoordData();

  // Update header to account for new data that was written
  m_NumFramesWritten++;

  m_FileStream.seekp(8);
  m_FileStream.write(reinterpret_cast<const char *>(&m_NumFramesWritten),
                     sizeof(int));

  int idum = m_NumFramesWritten * m_ReportFrequency;
  m_FileStream.seekp(20);
  m_FileStream.write(reinterpret_cast<const char *>(&idum), sizeof(int));

  m_FileStream.seekp(0, std::ofstream::end);

  return;
}

void DcdSubscriber::writeHeader(void) {
  std::array<char, 1024> buffer;
  int *iPtr = reinterpret_cast<int *>(buffer.data());
  float *fPtr = reinterpret_cast<float *>(buffer.data());
  int blockSizeBytes = 0;

  int start = 0; // JEG250610: Get this from integrator
  int nstep = 0; // This is updated as it is written
  int nsavv = 0;
  int ndegf = m_CharmmContext->getNumDegreesOfFreedom();
  int namnf = 0;
  float delta = m_Integrator->getTimeStep();
  bool hasXtalData = true;
  bool has4dData = false;
  bool hasCheqData = false;
  bool hasContData = false;
  int version = 49;

  // Fill input control block
  blockSizeBytes = 84;
  buffer.fill(0);
  iPtr[0] = 1146244931;        // 'C','O','R','D'
  iPtr[1] = 0;                 // Number of frames written (NFILE)
  iPtr[2] = start;             // Starting step (START)
  iPtr[3] = m_ReportFrequency; // Reporting frequency (NSAVC)
  iPtr[4] = nstep;  // Report frequency * number of frames written (NSTEP)
  iPtr[5] = nsavv;  // Velocity saving frequency (NSAVV)
  iPtr[6] = 0;      // UNUSED OPTION
  iPtr[7] = 0;      // UNUSED OPTION
  iPtr[8] = ndegf;  // Number of degrees of freedom (NDEGF)
  iPtr[9] = namnf;  // Number of fixed atoms (NAMNF)
  fPtr[10] = delta; // Time step (DELTA)
  iPtr[11] = (hasXtalData) ? 1 : 0;
  iPtr[12] = (has4dData) ? 1 : 0;
  iPtr[13] = (hasCheqData) ? 1 : 0;
  iPtr[14] = (hasContData) ? 1 : 0;
  iPtr[15] = 0;       // UNUSED OPTION
  iPtr[16] = 0;       // UNUSED OPTION
  iPtr[17] = 0;       // UNUSED OPTION
  iPtr[18] = 0;       // UNUSED OPTION
  iPtr[19] = 0;       // UNUSED OPTION
  iPtr[20] = version; // CHARMM version, should always be >= 22

  // Write start size of input control block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  // Write input control block
  m_FileStream.write(buffer.data(), blockSizeBytes);

  // Write end size of input control block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  // Fill title block
  blockSizeBytes = 164;
  buffer.fill(' ');
  iPtr[0] = 2;
  std::string title = "* GENERATED BY APOCHARMM";
  for (std::size_t i = 0; i < title.size(); i++)
    buffer[4 + i] = title[i];
  buffer[84] = '*';

  // Write start size of title block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  // Write title block
  m_FileStream.write(buffer.data(), blockSizeBytes);

  // Write end size of title block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  // Fill atom block
  blockSizeBytes = 4;
  buffer.fill(0);
  iPtr[0] = m_CharmmContext->getNumAtoms();

  // Write start size of atom block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  // Write atom block
  m_FileStream.write(buffer.data(), blockSizeBytes);

  // Write end size of atom block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  m_IsHeaderWritten = true;

  return;
}

void DcdSubscriber::writeXtalData(void) {
  std::array<char, 1024> buffer;
  double *dPtr = reinterpret_cast<double *>(buffer.data());
  int blockSizeBytes = 6 * static_cast<int>(sizeof(double));
  std::vector<double> boxDims = m_CharmmContext->getBoxDimensions();

  // Fille XTAL block
  buffer.fill(0);
  dPtr[0] = boxDims[0];
  dPtr[2] = boxDims[1];
  dPtr[5] = boxDims[2];

  // Write start size of XTAL block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  // Write XTAL block
  m_FileStream.write(buffer.data(), blockSizeBytes);

  // Write end size of XTAL block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  return;
}

void DcdSubscriber::writeCoordData(void) {
  // const std::shared_ptr<std::vector<float4>> ptr =
  //     m_CharmmContext->getXYZQ()->getHostXYZQ();
  // const float4 *xyzq = (*ptr).data();
  m_CharmmContext->getXYZQ().transferToHost();
  const float4 *xyzq = m_CharmmContext->getXYZQ().getHostArray().data();
  const int numAtoms = m_CharmmContext->getNumAtoms();
  const int blockSizeBytes = numAtoms * static_cast<int>(sizeof(float));

  // Write X coordinate block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));
  for (int i = 0; i < numAtoms; i++)
    m_FileStream.write(reinterpret_cast<const char *>(&xyzq[i].x),
                       sizeof(float));
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  // Write Y coordinate block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));
  for (int i = 0; i < numAtoms; i++)
    m_FileStream.write(reinterpret_cast<const char *>(&xyzq[i].y),
                       sizeof(float));
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  // Write Z coordinate block
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));
  for (int i = 0; i < numAtoms; i++)
    m_FileStream.write(reinterpret_cast<const char *>(&xyzq[i].z),
                       sizeof(float));
  m_FileStream.write(reinterpret_cast<const char *>(&blockSizeBytes),
                     sizeof(int));

  return;
}

/* *
struct DcdHeader {
  int size1;
  char cord[4];
  int ints1[9];
  float timeStep;
  int ints2[13];
  char str1[80];
  char str2[80];
  int last[4];
};

void DcdSubscriber::initialize(void) {
  if (!hasCharmmContext) {
    throw std::invalid_argument("DcdSubscriber does not have a CharmmContext, "
                                "can't initialize() properly.\n");
  }
  numAtoms = charmmContext->getNumAtoms();
  // Writing the headers
  int firstStep = 0; // TODO : get the firstStep from integrator
  // int interval = reportFreq;
  float timeStep = integrator->getTimeStep();
  int ndegf = charmmContext->getDegreesOfFreedom();
  // int boxFlag = 0;
  int boxFlag = 1; // adding unit cell dimensions

  DcdHeader header;
  header.size1 = 84;
  header.cord[0] = 'C';
  header.cord[1] = 'O';
  header.cord[2] = 'R';
  header.cord[3] = 'D';

  header.ints1[0] = 0; // number of frames written
  header.ints1[1] = firstStep;
  header.ints1[2] = reportFreq;
  header.ints1[3] = 0;     // reportFreq * number of frame written
  header.ints1[4] = 0;     // velocity saving frequency
  header.ints1[5] = 0;     // unused
  header.ints1[6] = 0;     // unused
  header.ints1[7] = ndegf; // ndegf
  header.ints1[8] = 0;     // Number of fixed atoms

  header.timeStep = timeStep;

  header.ints2[0] = boxFlag;
  header.ints2[1] = 0;  // 4d data
  header.ints2[2] = 0;  // cheq charge data
  header.ints2[3] = 0;  // non-contiguous data
  header.ints2[4] = 0;  // unused
  header.ints2[5] = 0;  // unused
  header.ints2[6] = 0;  // unused
  header.ints2[7] = 0;  // unused
  header.ints2[8] = 0;  // unused
  header.ints2[9] = 35; // CHARMM version, should be >= 22
  header.ints2[10] = 84;

  header.ints2[11] = 164;
  header.ints2[12] = 2;
  // header.str1 = "Created by CHARMM";
  // header.str2 = "Created at time ";
  header.last[0] = 164;

  header.last[1] = 4;
  header.last[2] = numAtoms;
  header.last[3] = 4;

  fout.write((char *)&header, sizeof(header));
  isInitialized = true;
}
* */
