on: [push]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10, 3.11, 3.12]
    steps:
    # checkout the code
    - name: checkout
      uses: actions/checkout@v3
    
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml

    #- name: Build wheels
    #  uses: pypa/cibbuildwheels-action@v2
