on:
  workflow_dispatch:
  push:

env:
  CONDA_ENV: apoenv
  FORCE_COLOR: 3
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    # checkout the code
    - name: checkout
      uses: actions/checkout@v3

    #- name: Set up python
    #  uses: actions/setup-python@v5
    #  with:
    #    python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
    
    - name: Install miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        activate-environment: ${{ env.CONDA_ENV }}
        auto-activate-base: false

    - name: Build and install
      shell: bash -l {0}
      run: |
        #conda run -n ${{ env.CONDA_ENV}} pip install --verbose .
        conda activate ${{ env.CONDA_ENV }}
        pip install nvidia-nvtx-cu12
        #pip install cibuildwheel
        pip install --verbose .
    #- name: Build wheels using cibuildwheel
    #  run: |
    #    conda run -n ${{ env.CONDA_ENV }} cibuildwheel --output-dir wheelhouse
    #  env:
    #    CIBW_BUILD: "cp38-manylinux_x86_64 cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64"
    #    CIBW_SKIP: "pp* *-musllinux*"
    #    CIBW_ARCHS_LINUX: "x86_64"
    #    CIBW_PLATFORM: "linux"

        
      #uses: pypa/cibbuildwheels-action@v2
