on:
  workflow_dispatch:
  push:

env:
  CONDA_ENV: apoenv
  FORCE_COLOR: 3
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    # checkout the code
    - name: checkout
      uses: actions/checkout@v3
    
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        activate-environment: ${{ env.CONDA_ENV }}
        auto-activate-base: false

    - name: Build and install
      shell: bash -l {0}
      run: |
        #conda run -n ${{ env.CONDA_ENV}} pip install --verbose .
        conda activate ${{ env.CONDA_ENV }}
        pip install nvidia-nvtx-cu12
        pip install --verbose .
        
      #uses: pypa/cibbuildwheels-action@v2
